### ISSUE TITLE
Баг с закладками

### ISSUE THREAD

**Issue by vovsemenv** [RTUITLab/StuDo-Front#22]
При нажатии на закладки происходит перенаправление на форму авторизации хоть я уже и вошел , а если все-же проходишь эту авторизацию, то никаких закладок не показывается. т.е невозможно каким либо образом получить доступ к закладкам.
## Сама кнопка
![image](https://user-images.githubusercontent.com/20096510/81535111-e1f8fc00-9371-11ea-8a59-6e0139cc3b59.png)
## Всплывает при нажатии на нее
![image](https://user-images.githubusercontent.com/20096510/81535142-f0471800-9371-11ea-8bcd-bb81e8c2f167.png)

**Comment by IvLaptev** [comment]
Частный случай #49
