### ISSUE TITLE
Сайт выкидывает пользователя

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/StuDo-Front#49]
Какой-то косяк с токеном. Авторизованный пользователь выкидывается с сайта через какое-то рандомное время. Возможно, дело в том, что accesstoken живёт 10 секунд, но почему тогда через 10 секунд я, работая с тем же токеном имею доступ к сайту? Очень странно.

**Comment by CAPCHIK** [comment]
Токен и правда живет 10 секунд

![image](https://user-images.githubusercontent.com/12235437/100231567-0e263580-2edc-11eb-850f-261bfabaae5c.png)
![image](https://user-images.githubusercontent.com/12235437/100231572-0f576280-2edc-11eb-9f71-400e3fc23095.png)

И раз на то пошло - то кажется iss и aud не совсем корректные

**Comment by IvLaptev** [comment]
Но при этом ты пользовался утром сайтом дольше чем 10 секунд, мне кажется
